complexity:
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    threshold: 20

style:
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  ReturnCount:
    max: 3
  UnusedPrivateProperty:
    excludes:
      - "**/commonMain/**"
  UnusedParameter:
    excludes:
      - "**/KBigIntUtils.kt"
  MagicNumber:
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
      - "10"
    ignoreAnnotated:
      - Test
