[versions]
kotlin-stdlib = "1.9.23"
#noinspection GradleDependency
android-gradle = {strictly = "8.2.0"}

[libraries.kotlin-stdlib]
module = "org.jetbrains.kotlin:kotlin-stdlib"
version.ref = "kotlin-stdlib"

[plugins.kotlin-mpp]
id = "org.jetbrains.kotlin.multiplatform"
version.ref = "kotlin-stdlib"

[plugins.kotlin-serialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin-stdlib"

[plugins.android-library]
id = "com.android.library"
version.ref = "android-gradle"
