name: CI

on:
  push:
    branches: [master]
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - gradle/**
  pull_request:
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - gradle/**

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref_name}}

permissions:
  contents: write

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: Test ${{matrix.platform}} platform
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            platform: JVM
            targets: jvmTest
          - os: ubuntu-22.04
            platform: Android
            targets: testReleaseUnitTest
          - os: ubuntu-22.04
            platform: JS
            targets: jsNodeTest jsBrowserTest
          - os: ubuntu-22.04
            platform: Linux
            targets: compileKotlinLinuxArm64 linuxX64Test
          - os: windows-latest
            platform: Windows
            targets: mingwX64Test
          - os: macos-13
            platform: macOS/iOS (x64)
            targets: macosX64Test iosX64Test
          - os: macos-14
            platform: macOS/iOS (arm64)
            targets: macosArm64Test iosSimulatorArm64Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            gradle/libs.versions.toml
            gradle/wrapper/gradle-wrapper.properties
      - name: Set up Chromium
        uses: browser-actions/setup-chrome@v2
        id: chromium
        if: matrix.platform == 'JS'
      - name: Set up cross compilation
        run: sudo apt-get install -qy {binutils,gcc}-aarch64-linux-gnu
        if: matrix.platform == 'Linux'
      - name: Get the cache versions
        id: versions
        shell: sh
        run: |-
          {
            sed -n 's/kotlin-stdlib = "\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)"/kotlin=\1.\2.\3/p' gradle/libs.versions.toml
          } >> "$GITHUB_OUTPUT"
      - name: Cache Kotlin/Native prebuilt
        uses: actions/cache@v4
        with:
          path: ${{runner.tool_cache}}/konan/kotlin-native-prebuilt-*
          key: konan-${{runner.os}}-prebuilt-${{steps.versions.outputs.kotlin}}
      - name: Cache Kotlin/Native dependencies
        uses: actions/cache@v4
        if: matrix.platform != 'JVM' && matrix.platform != 'Android' && matrix.platform != 'JS'
        with:
          path: ${{runner.tool_cache}}/konan/dependencies
          key: konan-${{runner.os}}-dependencies
      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        if: github.ref_name == 'master'
        with:
          cache-disabled: true
          add-job-summary: never
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
      - name: Run tests
        run: ./gradlew --no-daemon ${{matrix.targets}}
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
