name: CI

on:
  push:
    branches: [master]
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - gradle/**
      - gradle.properties
  pull_request:
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - gradle/**
      - gradle.properties

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref_name}}

permissions:
  contents: write

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: Test ${{matrix.platform}} platform
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: jvmTest, platform: jvm }
          - { os: ubuntu-latest, target: testReleaseUnitTest, platform: android }

          - { os: ubuntu-latest, target: jsNodeTest, platform: node }
          - { os: ubuntu-latest, target: jsBrowserTest, platform: browser }

          - { os: ubuntu-latest, target: linuxX64Test, platform: linux-x64 }
          - { os: ubuntu-latest, target: compileKotlinLinuxArm64, platform: linux-arm64 }

          - { os: windows-latest, target: mingwX64Test, platform: windows-x64 }

          - { os: macos-13, target: macosX64Test, platform: macos-x64 }
          - { os: macos-14, target: macosArm64Test, platform: macos-arm64 }
          - { os: macos-14, target: iosSimulatorArm64Test, platform: ios-arm64 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            gradle/libs.versions.toml
            gradle/wrapper/gradle-wrapper.properties
      - name: Set up Chromium
        uses: browser-actions/setup-chrome@v1
        id: chromium
        if: matrix.platform == 'browser'
      - name: Set up cross compilation
        run: sudo apt-get install -qy {binutils,gcc}-aarch64-linux-gnu
        if: matrix.platform == 'linux-arm64'
      - name: Get the Kotlin version
        id: kotlin
        shell: sh
        run: >-
          sed -n 's/kotlin-stdlib = "\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)"/version=\1\2\3/p'
          gradle/libs.versions.toml >> "$GITHUB_OUTPUT"
      - name: Cache Kotlin/Native prebuilt
        uses: actions/cache@v4
        with:
          path: ${{runner.tool_cache}}/konan/kotlin-native-prebuilt-*
          key: konan-${{matrix.os}}-prebuilt-${{steps.kotlin.outputs.version}}
      - name: Cache Kotlin/Native dependencies
        uses: actions/cache@v4
        if: endsWith(matrix.platform, '64')
        with:
          path: ${{runner.tool_cache}}/konan/dependencies
          key: >-
            konan-${{matrix.os}}-dependencies-${{
            matrix.platform == 'ios-arm64' && 'macos-arm64' || matrix.platform}}
      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        if: github.ref_name == 'master'
        with:
          cache-disabled: true
          add-job-summary: never
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
      - name: Run tests
        run: ./gradlew --no-daemon ${{matrix.target}}
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
