name: Docs

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [master]

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref_name}}

permissions:
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Publish docs on GitHub pages
    if: github.event.workflow_run.conclusion == 'success'
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            gradle/libs.versions.toml
            gradle/wrapper/gradle-wrapper.properties
      - name: Set up cross compilation
        run: sudo apt-get install -qy {binutils,gcc}-aarch64-linux-gnu
      - name: Get the Kotlin version
        id: kotlin
        shell: sh
        run: >-
          sed -n 's/kotlin-stdlib = "\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)"/version=\1\2\3/p'
          gradle/libs.versions.toml >> "$GITHUB_OUTPUT"
      - name: Restore Kotlin/Native prebuilt
        uses: actions/cache/restore@v4
        with:
          path: ${{runner.tool_cache}}/konan/kotlin-native-prebuilt-*
          key: konan-ubuntu-latest-prebuilt-${{steps.kotlin.outputs.version}}
      - name: Restore Kotlin/Native dependencies (x64)
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{runner.tool_cache}}/konan/dependencies/libffi-*
            ${{runner.tool_cache}}/konan/dependencies/lldb-*
            ${{runner.tool_cache}}/konan/dependencies/llvm-*
            ${{runner.tool_cache}}/konan/dependencies/x86_64-*
          key: konan-ubuntu-latest-dependencies-linux-x64
      - name: Restore Kotlin/Native dependencies (arm64)
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{runner.tool_cache}}/konan/dependencies/aarch64-*
            ${{runner.tool_cache}}/konan/dependencies/qemu-*
          key: konan-ubuntu-latest-dependencies-linux-arm64
      - name: Build documentation
        run: ./gradlew --no-daemon dokkaHtmlMultiModule
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/htmlMultiModule
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
