name: Docs

run-name: ${{github.event.workflow_run.head_commit.message}}

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [master]

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref_name}}

permissions:
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Publish docs on GitHub pages
    if: github.event.workflow_run.conclusion == 'success'
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            gradle/libs.versions.toml
            gradle/wrapper/gradle-wrapper.properties
      - name: Set up cross compilation
        run: sudo apt-get install -qy {binutils,gcc}-aarch64-linux-gnu gcc-mingw-w64-x86-64-posix
      - name: Get the cache versions
        id: versions
        shell: sh
        run: |-
          {
            sed -n 's/kotlin-stdlib = "\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)"/kotlin=\1.\2.\3/p' gradle/libs.versions.toml
          } >> "$GITHUB_OUTPUT"
      - name: Restore Kotlin/Native prebuilt
        uses: actions/cache/restore@v4
        with:
          path: ${{runner.tool_cache}}/konan/kotlin-native-prebuilt-*
          key: konan-${{runner.os}}-prebuilt-${{steps.versions.outputs.kotlin}}
      - name: Restore Kotlin/Native dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{runner.tool_cache}}/konan/dependencies
          key: konan-${{runner.os}}-dependencies
      - name: Build documentation
        run: ./gradlew --no-daemon dokkaGeneratePublicationHtml
        env:
          KONAN_DATA_DIR: ${{runner.tool_cache}}/konan
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
